### ISSUE TITLE
这个组织是干什么的

### ISSUE THREAD

**Issue by zeruniverse** [V2Git/README#1]
而且我居然有owner权限……

**Comment by ZoharWang** [comment]
https://www.v2ex.com/t/278487

**Comment by YUX-IO** [comment]
当时我手滑了点了个owner (ノ°ο°)ノ，嘿嘿嘿，其实是因为你是我第一个邀请的人(/ω＼)

On 周六, 5月 14, 2016 at 11:02 上午, Zohar Wang <notifications@github.com> wrote:
https://www.v2ex.com/t/278487 [https://www.v2ex.com/t/278487]

**Comment by zeruniverse** [comment]
Got it. Thanks.

那我觉得最好写个README吧。

**Comment by wsdjeg** [comment]
@zeruniverse 最好写明这个组织的目的,目前看不出来到底想干什么.

**Comment by zeruniverse** [comment]
Need a README

**Comment by YUX-IO** [comment]
我今天写出来

**Comment by wsdjeg** [comment]
仓库名称需要改掉，我觉得issues就不错，不需要大写，大家有什么问题就可以在这个仓库的issue中讨论，得出的一些结论，结果可以更新在readme中，这样，大家一打开仓库就了解到这个组织是做什么的，并且了解到大家在讨论什么！

**Comment by YUX-IO** [comment]
写完了

**Comment by wsdjeg** [comment]
不错！

**Comment by YUX-IO** [comment]
(ノ°ο°)ノ @wsdjeg 给你owner咯

**Comment by wsdjeg** [comment]
谢谢，刚收到邮件通知了。

**Comment by wsdjeg** [comment]
https://github.com/vim-jp/issues/issues

这个是一个不错的范例，可以参考这个来搞这个仓库

**Comment by YUX-IO** [comment]
@wsdjeg 好哟٩(ˊᗜˋ*)و
