### ISSUE TITLE
关于这个组织

### ISSUE THREAD

**Issue by wsdjeg** [V2Git/README#14]
最近，由于打开了邮件通知，发现很多加入的用户，将自己的仓库 fork 到组织，然而并不是在组织里面维护，我可以理解为变相的邮件 spam 吗？

现在关闭直接新建仓库权限，需要在组织里面新建仓库，请在此仓库留言。

**Comment by wsdjeg** [comment]
@YUX-IO 你好，请问，现在这个组织到底要怎么弄？搞个项目目录什么的我想会好一点吧？ 否则你看 目前的 20 + fork 的仓库也没啥意义呀。

**Comment by wsdjeg** [comment]
@YUX-IO 不好意思，操作不当，我邀请你回组织了。

**Comment by YUX-IO** [comment]
不好意思 刚高考完 麻烦你了

**Comment by qex** [comment]
@YUX-IO 同申请加入组织

**Comment by wsdjeg** [comment]
已邀请

**Comment by qex** [comment]
@wsdjeg 万分感谢
